// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: health.sql

package db

import (
	"context"
	"database/sql"
)

const createHealthCheck = `-- name: CreateHealthCheck :one
INSERT INTO health_checks (
    status,
    message,
    open_connections,
    in_use,
    idle,
    wait_count,
    wait_duration,
    max_idle_closed,
    max_lifetime_closed
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
) RETURNING id, status, message, open_connections, in_use, idle, wait_count, wait_duration, max_idle_closed, max_lifetime_closed, created_at
`

type CreateHealthCheckParams struct {
	Status            string         `json:"status"`
	Message           sql.NullString `json:"message"`
	OpenConnections   sql.NullInt64  `json:"open_connections"`
	InUse             sql.NullInt64  `json:"in_use"`
	Idle              sql.NullInt64  `json:"idle"`
	WaitCount         sql.NullInt64  `json:"wait_count"`
	WaitDuration      sql.NullString `json:"wait_duration"`
	MaxIdleClosed     sql.NullInt64  `json:"max_idle_closed"`
	MaxLifetimeClosed sql.NullInt64  `json:"max_lifetime_closed"`
}

func (q *Queries) CreateHealthCheck(ctx context.Context, arg CreateHealthCheckParams) (HealthCheck, error) {
	row := q.db.QueryRowContext(ctx, createHealthCheck,
		arg.Status,
		arg.Message,
		arg.OpenConnections,
		arg.InUse,
		arg.Idle,
		arg.WaitCount,
		arg.WaitDuration,
		arg.MaxIdleClosed,
		arg.MaxLifetimeClosed,
	)
	var i HealthCheck
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Message,
		&i.OpenConnections,
		&i.InUse,
		&i.Idle,
		&i.WaitCount,
		&i.WaitDuration,
		&i.MaxIdleClosed,
		&i.MaxLifetimeClosed,
		&i.CreatedAt,
	)
	return i, err
}

const getHealthChecks = `-- name: GetHealthChecks :many
SELECT id, status, message, open_connections, in_use, idle, wait_count, wait_duration, max_idle_closed, max_lifetime_closed, created_at FROM health_checks
ORDER BY created_at DESC
LIMIT ?
`

func (q *Queries) GetHealthChecks(ctx context.Context, limit int64) ([]HealthCheck, error) {
	rows, err := q.db.QueryContext(ctx, getHealthChecks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HealthCheck
	for rows.Next() {
		var i HealthCheck
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Message,
			&i.OpenConnections,
			&i.InUse,
			&i.Idle,
			&i.WaitCount,
			&i.WaitDuration,
			&i.MaxIdleClosed,
			&i.MaxLifetimeClosed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestHealthCheck = `-- name: GetLatestHealthCheck :one
SELECT id, status, message, open_connections, in_use, idle, wait_count, wait_duration, max_idle_closed, max_lifetime_closed, created_at FROM health_checks
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestHealthCheck(ctx context.Context) (HealthCheck, error) {
	row := q.db.QueryRowContext(ctx, getLatestHealthCheck)
	var i HealthCheck
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Message,
		&i.OpenConnections,
		&i.InUse,
		&i.Idle,
		&i.WaitCount,
		&i.WaitDuration,
		&i.MaxIdleClosed,
		&i.MaxLifetimeClosed,
		&i.CreatedAt,
	)
	return i, err
}
