// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type HealthCheck struct {
	ID                int64          `json:"id"`
	Status            string         `json:"status"`
	Message           sql.NullString `json:"message"`
	OpenConnections   sql.NullInt64  `json:"open_connections"`
	InUse             sql.NullInt64  `json:"in_use"`
	Idle              sql.NullInt64  `json:"idle"`
	WaitCount         sql.NullInt64  `json:"wait_count"`
	WaitDuration      sql.NullString `json:"wait_duration"`
	MaxIdleClosed     sql.NullInt64  `json:"max_idle_closed"`
	MaxLifetimeClosed sql.NullInt64  `json:"max_lifetime_closed"`
	CreatedAt         sql.NullTime   `json:"created_at"`
}
