// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateHealthCheck(ctx context.Context, arg CreateHealthCheckParams) (HealthCheck, error)
	GetHealthChecks(ctx context.Context, limit int64) ([]HealthCheck, error)
	GetLatestHealthCheck(ctx context.Context) (HealthCheck, error)
}

var _ Querier = (*Queries)(nil)
