// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"context"
)

type Querier interface {
	CreatePortfolio(ctx context.Context, arg CreatePortfolioParams) (Portfolio, error)
	DeletePortfolio(ctx context.Context, id int64) error
	// queries.sql
	GetAllPortfolios(ctx context.Context) ([]Portfolio, error)
	GetLatestPortfolio(ctx context.Context) (Portfolio, error)
}

var _ Querier = (*Queries)(nil)
