# Screen
DEFAULT_WIDTH = 240
DEFAULT_HEIGHT = 180
DEFAULT_FPS = 30
DEFAULT_GRID_SIZE = 10

# Widgets
WIDGET_MARGIN = 5
WIDGET_PADDING = 3

# Colors
COLOR_BG = 0  # Black
COLOR_GRID = 5  # Dark purple
COLOR_BORDER = 13  # Light gray
COLOR_TEXT = 7  # White
COLOR_WIDGET_BG = 1  # Dark blue
COLOR_BUTTON_ACTIVE = 11  # Yellow
COLOR_BUTTON_HOVER = 9  # Orange
COLOR_BUTTON_INACTIVE = 5  # Dark purple
COLOR_GRAPH_LINE = 11  # Yellow

# Line Graph Widget
LINE_GRAPH_WIDTH = 120
LINE_GRAPH_HEIGHT = 80
LINE_GRAPH_INITIAL_X = (DEFAULT_WIDTH - LINE_GRAPH_WIDTH) // 2
LINE_GRAPH_INITIAL_Y = (DEFAULT_HEIGHT - LINE_GRAPH_HEIGHT) // 2

# Button Widget
BUTTON_WIDTH = 60
BUTTON_HEIGHT = 15
BUTTON_INITIAL_X = DEFAULT_WIDTH - BUTTON_WIDTH - 10
BUTTON_INITIAL_Y = 10

# Game Settings