[project]
name = "dumbfi"
version = "0.0.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyxel>=2.3.17",
    "requests>=2.32.3",
    "pandas>=2.2.3",
    "yfinance>=0.2.55",
    "lxml>=5.3.1",
]
