// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package db

import (
	"context"
	"time"
)

const createPortfolio = `-- name: CreatePortfolio :one
INSERT INTO portfolios (cash, timestamp)
VALUES (?, ?) RETURNING id, cash, timestamp
`

type CreatePortfolioParams struct {
	Cash      float64
	Timestamp time.Time
}

func (q *Queries) CreatePortfolio(ctx context.Context, arg CreatePortfolioParams) (Portfolio, error) {
	row := q.db.QueryRowContext(ctx, createPortfolio, arg.Cash, arg.Timestamp)
	var i Portfolio
	err := row.Scan(&i.ID, &i.Cash, &i.Timestamp)
	return i, err
}

const deletePortfolio = `-- name: DeletePortfolio :exec
DELETE FROM portfolios 
WHERE id = ?
`

func (q *Queries) DeletePortfolio(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePortfolio, id)
	return err
}

const getAllPortfolios = `-- name: GetAllPortfolios :many
SELECT id, cash, timestamp FROM portfolios ORDER BY timestamp DESC
`

// queries.sql
func (q *Queries) GetAllPortfolios(ctx context.Context) ([]Portfolio, error) {
	rows, err := q.db.QueryContext(ctx, getAllPortfolios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Portfolio{}
	for rows.Next() {
		var i Portfolio
		if err := rows.Scan(&i.ID, &i.Cash, &i.Timestamp); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestPortfolio = `-- name: GetLatestPortfolio :one
SELECT id, cash, timestamp FROM portfolios 
ORDER BY timestamp DESC 
LIMIT 1
`

func (q *Queries) GetLatestPortfolio(ctx context.Context) (Portfolio, error) {
	row := q.db.QueryRowContext(ctx, getLatestPortfolio)
	var i Portfolio
	err := row.Scan(&i.ID, &i.Cash, &i.Timestamp)
	return i, err
}
