// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package models

import (
	"database/sql"
	"time"
)

type Account struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	Cash      float64      `json:"cash"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Holding struct {
	ID            int64           `json:"id"`
	AccountID     int64           `json:"account_id"`
	Symbol        string          `json:"symbol"`
	Quantity      int64           `json:"quantity"`
	AvgPrice      float64         `json:"avg_price"`
	MarketValue   sql.NullFloat64 `json:"market_value"`
	UnrealizedPnl sql.NullFloat64 `json:"unrealized_pnl"`
	CreatedAt     sql.NullTime    `json:"created_at"`
	UpdatedAt     sql.NullTime    `json:"updated_at"`
}

type TaxLot struct {
	ID                int64        `json:"id"`
	AccountID         int64        `json:"account_id"`
	HoldingID         int64        `json:"holding_id"`
	Symbol            string       `json:"symbol"`
	Quantity          int64        `json:"quantity"`
	RemainingQuantity int64        `json:"remaining_quantity"`
	CostBasis         float64      `json:"cost_basis"`
	PurchaseDate      time.Time    `json:"purchase_date"`
	Status            string       `json:"status"`
	CreatedAt         sql.NullTime `json:"created_at"`
}

type Trade struct {
	ID          int64           `json:"id"`
	AccountID   int64           `json:"account_id"`
	TaxLotID    int64           `json:"tax_lot_id"`
	Symbol      string          `json:"symbol"`
	Side        string          `json:"side"`
	Quantity    int64           `json:"quantity"`
	Price       float64         `json:"price"`
	TradeDate   time.Time       `json:"trade_date"`
	Strategy    string          `json:"strategy"`
	Commission  sql.NullFloat64 `json:"commission"`
	RealizedPnl sql.NullFloat64 `json:"realized_pnl"`
	Notes       sql.NullString  `json:"notes"`
	CreatedAt   sql.NullTime    `json:"created_at"`
}
