// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package models

import (
	"context"
	"database/sql"
	"time"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    name,
    cash
) VALUES (?, ?) RETURNING id, name, cash, created_at, updated_at
`

type CreateAccountParams struct {
	Name string  `json:"name"`
	Cash float64 `json:"cash"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount, arg.Name, arg.Cash)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLot = `-- name: CreateLot :one
INSERT INTO tax_lots (
    account_id,
    holding_id,
    symbol,
    quantity,
    remaining_quantity,
    cost_basis,
    purchase_date,
    status
) VALUES (?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, account_id, holding_id, symbol, quantity, remaining_quantity, cost_basis, purchase_date, status, created_at
`

type CreateLotParams struct {
	AccountID         int64     `json:"account_id"`
	HoldingID         int64     `json:"holding_id"`
	Symbol            string    `json:"symbol"`
	Quantity          int64     `json:"quantity"`
	RemainingQuantity int64     `json:"remaining_quantity"`
	CostBasis         float64   `json:"cost_basis"`
	PurchaseDate      time.Time `json:"purchase_date"`
	Status            string    `json:"status"`
}

func (q *Queries) CreateLot(ctx context.Context, arg CreateLotParams) (TaxLot, error) {
	row := q.db.QueryRowContext(ctx, createLot,
		arg.AccountID,
		arg.HoldingID,
		arg.Symbol,
		arg.Quantity,
		arg.RemainingQuantity,
		arg.CostBasis,
		arg.PurchaseDate,
		arg.Status,
	)
	var i TaxLot
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.HoldingID,
		&i.Symbol,
		&i.Quantity,
		&i.RemainingQuantity,
		&i.CostBasis,
		&i.PurchaseDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createTrade = `-- name: CreateTrade :one
INSERT INTO trades (
    account_id,
    tax_lot_id,
    symbol,
    side,
    quantity,
    price,
    trade_date,
    strategy,
    commission,
    realized_pnl,
    notes
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, account_id, tax_lot_id, symbol, side, quantity, price, trade_date, strategy, commission, realized_pnl, notes, created_at
`

type CreateTradeParams struct {
	AccountID   int64           `json:"account_id"`
	TaxLotID    int64           `json:"tax_lot_id"`
	Symbol      string          `json:"symbol"`
	Side        string          `json:"side"`
	Quantity    int64           `json:"quantity"`
	Price       float64         `json:"price"`
	TradeDate   time.Time       `json:"trade_date"`
	Strategy    string          `json:"strategy"`
	Commission  sql.NullFloat64 `json:"commission"`
	RealizedPnl sql.NullFloat64 `json:"realized_pnl"`
	Notes       sql.NullString  `json:"notes"`
}

func (q *Queries) CreateTrade(ctx context.Context, arg CreateTradeParams) (Trade, error) {
	row := q.db.QueryRowContext(ctx, createTrade,
		arg.AccountID,
		arg.TaxLotID,
		arg.Symbol,
		arg.Side,
		arg.Quantity,
		arg.Price,
		arg.TradeDate,
		arg.Strategy,
		arg.Commission,
		arg.RealizedPnl,
		arg.Notes,
	)
	var i Trade
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TaxLotID,
		&i.Symbol,
		&i.Side,
		&i.Quantity,
		&i.Price,
		&i.TradeDate,
		&i.Strategy,
		&i.Commission,
		&i.RealizedPnl,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = ?
`

func (q *Queries) DeleteAccount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, id)
	return err
}

const deleteHolding = `-- name: DeleteHolding :exec
DELETE FROM holdings WHERE id = ?
`

func (q *Queries) DeleteHolding(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteHolding, id)
	return err
}

const deleteTaxLot = `-- name: DeleteTaxLot :exec
DELETE FROM tax_lots WHERE id = ?
`

func (q *Queries) DeleteTaxLot(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTaxLot, id)
	return err
}

const deleteTrade = `-- name: DeleteTrade :exec
DELETE FROM trades WHERE id = ?
`

func (q *Queries) DeleteTrade(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTrade, id)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, cash, created_at, updated_at FROM accounts WHERE id = ?
`

func (q *Queries) GetAccount(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountPerformance = `-- name: GetAccountPerformance :one
SELECT 
    a.id,
    a.name,
    a.cash,
    COALESCE(SUM(h.market_value), 0) as total_market_value,
    COALESCE(SUM(h.unrealized_pnl), 0) as total_unrealized_pnl,
    COALESCE((SELECT SUM(realized_pnl) FROM trades WHERE account_id = a.id), 0) as total_realized_pnl
FROM accounts a
LEFT JOIN holdings h ON h.account_id = a.id
WHERE a.id = ?
GROUP BY a.id, a.name, a.cash
`

type GetAccountPerformanceRow struct {
	ID                 int64       `json:"id"`
	Name               string      `json:"name"`
	Cash               float64     `json:"cash"`
	TotalMarketValue   interface{} `json:"total_market_value"`
	TotalUnrealizedPnl interface{} `json:"total_unrealized_pnl"`
	TotalRealizedPnl   interface{} `json:"total_realized_pnl"`
}

func (q *Queries) GetAccountPerformance(ctx context.Context, id int64) (GetAccountPerformanceRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountPerformance, id)
	var i GetAccountPerformanceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cash,
		&i.TotalMarketValue,
		&i.TotalUnrealizedPnl,
		&i.TotalRealizedPnl,
	)
	return i, err
}

const getHolding = `-- name: GetHolding :one
SELECT id, account_id, symbol, quantity, avg_price, market_value, unrealized_pnl, created_at, updated_at FROM holdings WHERE id = ?
`

func (q *Queries) GetHolding(ctx context.Context, id int64) (Holding, error) {
	row := q.db.QueryRowContext(ctx, getHolding, id)
	var i Holding
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Symbol,
		&i.Quantity,
		&i.AvgPrice,
		&i.MarketValue,
		&i.UnrealizedPnl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHoldingBySymbol = `-- name: GetHoldingBySymbol :one
SELECT id, account_id, symbol, quantity, avg_price, market_value, unrealized_pnl, created_at, updated_at FROM holdings 
WHERE account_id = ? AND symbol = ?
`

type GetHoldingBySymbolParams struct {
	AccountID int64  `json:"account_id"`
	Symbol    string `json:"symbol"`
}

func (q *Queries) GetHoldingBySymbol(ctx context.Context, arg GetHoldingBySymbolParams) (Holding, error) {
	row := q.db.QueryRowContext(ctx, getHoldingBySymbol, arg.AccountID, arg.Symbol)
	var i Holding
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Symbol,
		&i.Quantity,
		&i.AvgPrice,
		&i.MarketValue,
		&i.UnrealizedPnl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLot = `-- name: GetLot :one
SELECT id, account_id, holding_id, symbol, quantity, remaining_quantity, cost_basis, purchase_date, status, created_at FROM tax_lots WHERE id = ?
`

func (q *Queries) GetLot(ctx context.Context, id int64) (TaxLot, error) {
	row := q.db.QueryRowContext(ctx, getLot, id)
	var i TaxLot
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.HoldingID,
		&i.Symbol,
		&i.Quantity,
		&i.RemainingQuantity,
		&i.CostBasis,
		&i.PurchaseDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getSymbolPerformance = `-- name: GetSymbolPerformance :one
SELECT 
    symbol,
    SUM(CASE WHEN side = 'buy' THEN quantity ELSE -quantity END) as net_quantity,
    AVG(CASE WHEN side = 'buy' THEN price ELSE NULL END) as avg_buy_price,
    AVG(CASE WHEN side = 'sell' THEN price ELSE NULL END) as avg_sell_price,
    SUM(COALESCE(realized_pnl, 0)) as total_realized_pnl,
    COUNT(CASE WHEN side = 'buy' THEN 1 END) as buy_trades,
    COUNT(CASE WHEN side = 'sell' THEN 1 END) as sell_trades
FROM trades
WHERE account_id = ? AND symbol = ?
GROUP BY symbol
`

type GetSymbolPerformanceParams struct {
	AccountID int64  `json:"account_id"`
	Symbol    string `json:"symbol"`
}

type GetSymbolPerformanceRow struct {
	Symbol           string          `json:"symbol"`
	NetQuantity      sql.NullFloat64 `json:"net_quantity"`
	AvgBuyPrice      sql.NullFloat64 `json:"avg_buy_price"`
	AvgSellPrice     sql.NullFloat64 `json:"avg_sell_price"`
	TotalRealizedPnl sql.NullFloat64 `json:"total_realized_pnl"`
	BuyTrades        int64           `json:"buy_trades"`
	SellTrades       int64           `json:"sell_trades"`
}

func (q *Queries) GetSymbolPerformance(ctx context.Context, arg GetSymbolPerformanceParams) (GetSymbolPerformanceRow, error) {
	row := q.db.QueryRowContext(ctx, getSymbolPerformance, arg.AccountID, arg.Symbol)
	var i GetSymbolPerformanceRow
	err := row.Scan(
		&i.Symbol,
		&i.NetQuantity,
		&i.AvgBuyPrice,
		&i.AvgSellPrice,
		&i.TotalRealizedPnl,
		&i.BuyTrades,
		&i.SellTrades,
	)
	return i, err
}

const getTaxLotsByFIFO = `-- name: GetTaxLotsByFIFO :many
SELECT id, account_id, holding_id, symbol, quantity, remaining_quantity, cost_basis, purchase_date, status, created_at FROM tax_lots
WHERE account_id = ?
  AND symbol = ?
  AND remaining_quantity > 0
  AND status IN ('open', 'partial')
ORDER BY purchase_date ASC
`

type GetTaxLotsByFIFOParams struct {
	AccountID int64  `json:"account_id"`
	Symbol    string `json:"symbol"`
}

func (q *Queries) GetTaxLotsByFIFO(ctx context.Context, arg GetTaxLotsByFIFOParams) ([]TaxLot, error) {
	rows, err := q.db.QueryContext(ctx, getTaxLotsByFIFO, arg.AccountID, arg.Symbol)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaxLot
	for rows.Next() {
		var i TaxLot
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.HoldingID,
			&i.Symbol,
			&i.Quantity,
			&i.RemainingQuantity,
			&i.CostBasis,
			&i.PurchaseDate,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaxLotsByLIFO = `-- name: GetTaxLotsByLIFO :many
SELECT id, account_id, holding_id, symbol, quantity, remaining_quantity, cost_basis, purchase_date, status, created_at FROM tax_lots
WHERE account_id = ?
  AND symbol = ?
  AND remaining_quantity > 0
  AND status IN ('open', 'partial')
ORDER BY purchase_date DESC
`

type GetTaxLotsByLIFOParams struct {
	AccountID int64  `json:"account_id"`
	Symbol    string `json:"symbol"`
}

func (q *Queries) GetTaxLotsByLIFO(ctx context.Context, arg GetTaxLotsByLIFOParams) ([]TaxLot, error) {
	rows, err := q.db.QueryContext(ctx, getTaxLotsByLIFO, arg.AccountID, arg.Symbol)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaxLot
	for rows.Next() {
		var i TaxLot
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.HoldingID,
			&i.Symbol,
			&i.Quantity,
			&i.RemainingQuantity,
			&i.CostBasis,
			&i.PurchaseDate,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrade = `-- name: GetTrade :one
SELECT id, account_id, tax_lot_id, symbol, side, quantity, price, trade_date, strategy, commission, realized_pnl, notes, created_at FROM trades WHERE id = ?
`

func (q *Queries) GetTrade(ctx context.Context, id int64) (Trade, error) {
	row := q.db.QueryRowContext(ctx, getTrade, id)
	var i Trade
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TaxLotID,
		&i.Symbol,
		&i.Side,
		&i.Quantity,
		&i.Price,
		&i.TradeDate,
		&i.Strategy,
		&i.Commission,
		&i.RealizedPnl,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getTradesByDateRange = `-- name: GetTradesByDateRange :many
SELECT id, account_id, tax_lot_id, symbol, side, quantity, price, trade_date, strategy, commission, realized_pnl, notes, created_at FROM trades
WHERE account_id = ?
  AND trade_date BETWEEN ? AND ?
ORDER BY trade_date
`

func (q *Queries) GetTradesByDateRange(ctx context.Context, accountID int64) ([]Trade, error) {
	rows, err := q.db.QueryContext(ctx, getTradesByDateRange, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trade
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TaxLotID,
			&i.Symbol,
			&i.Side,
			&i.Quantity,
			&i.Price,
			&i.TradeDate,
			&i.Strategy,
			&i.Commission,
			&i.RealizedPnl,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountHoldings = `-- name: ListAccountHoldings :many
SELECT h.id, h.account_id, h.symbol, h.quantity, h.avg_price, h.market_value, h.unrealized_pnl, h.created_at, h.updated_at, a.name as account_name, a.cash as account_cash
FROM holdings h
JOIN accounts a ON h.account_id = a.id
WHERE h.account_id = ?
ORDER BY h.market_value DESC
`

type ListAccountHoldingsRow struct {
	ID            int64           `json:"id"`
	AccountID     int64           `json:"account_id"`
	Symbol        string          `json:"symbol"`
	Quantity      int64           `json:"quantity"`
	AvgPrice      float64         `json:"avg_price"`
	MarketValue   sql.NullFloat64 `json:"market_value"`
	UnrealizedPnl sql.NullFloat64 `json:"unrealized_pnl"`
	CreatedAt     sql.NullTime    `json:"created_at"`
	UpdatedAt     sql.NullTime    `json:"updated_at"`
	AccountName   string          `json:"account_name"`
	AccountCash   float64         `json:"account_cash"`
}

func (q *Queries) ListAccountHoldings(ctx context.Context, accountID int64) ([]ListAccountHoldingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccountHoldings, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountHoldingsRow
	for rows.Next() {
		var i ListAccountHoldingsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Symbol,
			&i.Quantity,
			&i.AvgPrice,
			&i.MarketValue,
			&i.UnrealizedPnl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountName,
			&i.AccountCash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountTaxLots = `-- name: ListAccountTaxLots :many
SELECT l.id, l.account_id, l.holding_id, l.symbol, l.quantity, l.remaining_quantity, l.cost_basis, l.purchase_date, l.status, l.created_at, h.avg_price as holding_avg_price, h.market_value as holding_market_value
FROM tax_lots l
JOIN holdings h ON l.holding_id = h.id
WHERE l.account_id = ?
ORDER BY l.purchase_date
`

type ListAccountTaxLotsRow struct {
	ID                 int64           `json:"id"`
	AccountID          int64           `json:"account_id"`
	HoldingID          int64           `json:"holding_id"`
	Symbol             string          `json:"symbol"`
	Quantity           int64           `json:"quantity"`
	RemainingQuantity  int64           `json:"remaining_quantity"`
	CostBasis          float64         `json:"cost_basis"`
	PurchaseDate       time.Time       `json:"purchase_date"`
	Status             string          `json:"status"`
	CreatedAt          sql.NullTime    `json:"created_at"`
	HoldingAvgPrice    float64         `json:"holding_avg_price"`
	HoldingMarketValue sql.NullFloat64 `json:"holding_market_value"`
}

func (q *Queries) ListAccountTaxLots(ctx context.Context, accountID int64) ([]ListAccountTaxLotsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccountTaxLots, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountTaxLotsRow
	for rows.Next() {
		var i ListAccountTaxLotsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.HoldingID,
			&i.Symbol,
			&i.Quantity,
			&i.RemainingQuantity,
			&i.CostBasis,
			&i.PurchaseDate,
			&i.Status,
			&i.CreatedAt,
			&i.HoldingAvgPrice,
			&i.HoldingMarketValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountTrades = `-- name: ListAccountTrades :many
SELECT t.id, t.account_id, t.tax_lot_id, t.symbol, t.side, t.quantity, t.price, t.trade_date, t.strategy, t.commission, t.realized_pnl, t.notes, t.created_at, l.cost_basis as tax_lot_cost_basis, l.purchase_date as tax_lot_purchase_date
FROM trades t
LEFT JOIN tax_lots l ON t.lot_id = l.id
WHERE t.account_id = ?
ORDER BY t.trade_date DESC
`

type ListAccountTradesRow struct {
	ID                 int64           `json:"id"`
	AccountID          int64           `json:"account_id"`
	TaxLotID           int64           `json:"tax_lot_id"`
	Symbol             string          `json:"symbol"`
	Side               string          `json:"side"`
	Quantity           int64           `json:"quantity"`
	Price              float64         `json:"price"`
	TradeDate          time.Time       `json:"trade_date"`
	Strategy           string          `json:"strategy"`
	Commission         sql.NullFloat64 `json:"commission"`
	RealizedPnl        sql.NullFloat64 `json:"realized_pnl"`
	Notes              sql.NullString  `json:"notes"`
	CreatedAt          sql.NullTime    `json:"created_at"`
	TaxLotCostBasis    sql.NullFloat64 `json:"tax_lot_cost_basis"`
	TaxLotPurchaseDate sql.NullTime    `json:"tax_lot_purchase_date"`
}

func (q *Queries) ListAccountTrades(ctx context.Context, accountID int64) ([]ListAccountTradesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccountTrades, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountTradesRow
	for rows.Next() {
		var i ListAccountTradesRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TaxLotID,
			&i.Symbol,
			&i.Side,
			&i.Quantity,
			&i.Price,
			&i.TradeDate,
			&i.Strategy,
			&i.Commission,
			&i.RealizedPnl,
			&i.Notes,
			&i.CreatedAt,
			&i.TaxLotCostBasis,
			&i.TaxLotPurchaseDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, name, cash, created_at, updated_at FROM accounts ORDER BY id
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Cash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHoldingTaxLots = `-- name: ListHoldingTaxLots :many
SELECT id, account_id, holding_id, symbol, quantity, remaining_quantity, cost_basis, purchase_date, status, created_at FROM tax_lots 
WHERE holding_id = ? 
ORDER BY purchase_date
`

func (q *Queries) ListHoldingTaxLots(ctx context.Context, holdingID int64) ([]TaxLot, error) {
	rows, err := q.db.QueryContext(ctx, listHoldingTaxLots, holdingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaxLot
	for rows.Next() {
		var i TaxLot
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.HoldingID,
			&i.Symbol,
			&i.Quantity,
			&i.RemainingQuantity,
			&i.CostBasis,
			&i.PurchaseDate,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSymbolTrades = `-- name: ListSymbolTrades :many
SELECT id, account_id, tax_lot_id, symbol, side, quantity, price, trade_date, strategy, commission, realized_pnl, notes, created_at FROM trades 
WHERE account_id = ? AND symbol = ?
ORDER BY trade_date DESC
`

type ListSymbolTradesParams struct {
	AccountID int64  `json:"account_id"`
	Symbol    string `json:"symbol"`
}

func (q *Queries) ListSymbolTrades(ctx context.Context, arg ListSymbolTradesParams) ([]Trade, error) {
	rows, err := q.db.QueryContext(ctx, listSymbolTrades, arg.AccountID, arg.Symbol)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trade
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TaxLotID,
			&i.Symbol,
			&i.Side,
			&i.Quantity,
			&i.Price,
			&i.TradeDate,
			&i.Strategy,
			&i.Commission,
			&i.RealizedPnl,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountCash = `-- name: UpdateAccountCash :one
UPDATE accounts 
SET cash = cash + ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? 
RETURNING id, name, cash, created_at, updated_at
`

type UpdateAccountCashParams struct {
	Cash float64 `json:"cash"`
	ID   int64   `json:"id"`
}

func (q *Queries) UpdateAccountCash(ctx context.Context, arg UpdateAccountCashParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateAccountCash, arg.Cash, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateHolding = `-- name: UpdateHolding :one
UPDATE holdings
SET quantity = ?,
    avg_price = ?,
    market_value = ?,
    unrealized_pnl = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, account_id, symbol, quantity, avg_price, market_value, unrealized_pnl, created_at, updated_at
`

type UpdateHoldingParams struct {
	Quantity      int64           `json:"quantity"`
	AvgPrice      float64         `json:"avg_price"`
	MarketValue   sql.NullFloat64 `json:"market_value"`
	UnrealizedPnl sql.NullFloat64 `json:"unrealized_pnl"`
	ID            int64           `json:"id"`
}

func (q *Queries) UpdateHolding(ctx context.Context, arg UpdateHoldingParams) (Holding, error) {
	row := q.db.QueryRowContext(ctx, updateHolding,
		arg.Quantity,
		arg.AvgPrice,
		arg.MarketValue,
		arg.UnrealizedPnl,
		arg.ID,
	)
	var i Holding
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Symbol,
		&i.Quantity,
		&i.AvgPrice,
		&i.MarketValue,
		&i.UnrealizedPnl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateHoldingMarketValue = `-- name: UpdateHoldingMarketValue :one
UPDATE holdings
SET market_value = ?,
    unrealized_pnl = market_value - (avg_price * quantity),
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, account_id, symbol, quantity, avg_price, market_value, unrealized_pnl, created_at, updated_at
`

type UpdateHoldingMarketValueParams struct {
	MarketValue sql.NullFloat64 `json:"market_value"`
	ID          int64           `json:"id"`
}

func (q *Queries) UpdateHoldingMarketValue(ctx context.Context, arg UpdateHoldingMarketValueParams) (Holding, error) {
	row := q.db.QueryRowContext(ctx, updateHoldingMarketValue, arg.MarketValue, arg.ID)
	var i Holding
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Symbol,
		&i.Quantity,
		&i.AvgPrice,
		&i.MarketValue,
		&i.UnrealizedPnl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaxLotstatus = `-- name: UpdateTaxLotstatus :one
UPDATE tax_lots
SET status = ?,
    remaining_quantity = ?
WHERE id = ?
RETURNING id, account_id, holding_id, symbol, quantity, remaining_quantity, cost_basis, purchase_date, status, created_at
`

type UpdateTaxLotstatusParams struct {
	Status            string `json:"status"`
	RemainingQuantity int64  `json:"remaining_quantity"`
	ID                int64  `json:"id"`
}

func (q *Queries) UpdateTaxLotstatus(ctx context.Context, arg UpdateTaxLotstatusParams) (TaxLot, error) {
	row := q.db.QueryRowContext(ctx, updateTaxLotstatus, arg.Status, arg.RemainingQuantity, arg.ID)
	var i TaxLot
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.HoldingID,
		&i.Symbol,
		&i.Quantity,
		&i.RemainingQuantity,
		&i.CostBasis,
		&i.PurchaseDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const upsertHolding = `-- name: UpsertHolding :one
INSERT INTO holdings (
    account_id,
    symbol,
    quantity,
    avg_price,
    market_value,
    unrealized_pnl
) VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (account_id, symbol) DO UPDATE
SET quantity = quantity + excluded.quantity,
    avg_price = ((avg_price * quantity) + (excluded.quantity * excluded.avg_price)) 
               / (quantity + excluded.quantity),
    market_value = excluded.market_value,
    unrealized_pnl = excluded.unrealized_pnl,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, account_id, symbol, quantity, avg_price, market_value, unrealized_pnl, created_at, updated_at
`

type UpsertHoldingParams struct {
	AccountID     int64           `json:"account_id"`
	Symbol        string          `json:"symbol"`
	Quantity      int64           `json:"quantity"`
	AvgPrice      float64         `json:"avg_price"`
	MarketValue   sql.NullFloat64 `json:"market_value"`
	UnrealizedPnl sql.NullFloat64 `json:"unrealized_pnl"`
}

func (q *Queries) UpsertHolding(ctx context.Context, arg UpsertHoldingParams) (Holding, error) {
	row := q.db.QueryRowContext(ctx, upsertHolding,
		arg.AccountID,
		arg.Symbol,
		arg.Quantity,
		arg.AvgPrice,
		arg.MarketValue,
		arg.UnrealizedPnl,
	)
	var i Holding
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Symbol,
		&i.Quantity,
		&i.AvgPrice,
		&i.MarketValue,
		&i.UnrealizedPnl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
